Fix dumping of open object types. Bug notified by Kakadu, 2 Nov 2016.
Before ocaml 4.02 object types were represented as field list
with specific field called Pfield_var when object type is open.
After 4.02 type declaration was changed to
   | Ptyp_object of (string loc * attributes * core_type) list * closed_flag
        (* < l1:T1; ...; ln:Tn >     (flag = Closed)
           < l1:T1; ...; ln:Tn; .. > (flag = Open)
         *)
and camlp5 implementation was changed to return empty list in function
where we create Pfield_var. But in function where we create object type
(`ocaml_ptyp_object`) we were always creating Closed object. It is fixed now.

Demo: camlp5 generates closed types instead of open ones

$ cat opentyp.ml
type t = <f:int; .. >

$ ocamlfind opt opentyp.ml -c -dparsetree
[
  structure_item (opentyp.ml[1,0+0]..[1,0+21])
    Pstr_type Rec
    [
      type_declaration "t" (opentyp.ml[1,0+5]..[1,0+6]) (opentyp.ml[1,0+0]..[1,0+21])
        ptype_params =
          []
        ptype_cstrs =
          []
        ptype_kind =
          Ptype_abstract
        ptype_private = Public
        ptype_manifest =
          Some
            core_type (opentyp.ml[1,0+9]..[1,0+21])
              Ptyp_object Open
                method f
                  core_type (opentyp.ml[1,0+12]..[1,0+15])
                    Ptyp_constr "int" (opentyp.ml[1,0+12]..[1,0+15])
                    []
    ]
]

File "opentyp.ml", line 1, characters 0-21:
Error: A type variable is unbound in this type declaration.
In type < f : int; .. > as 'a the variable 'a is unbound
$ ocamlfind opt opentyp.ml -c -dparsetree -pp etc/camlp5o
[
  structure_item (opentyp.ml[1,0+0]..[1,0+21])
    Pstr_type Rec
    [
      type_declaration "t" (opentyp.ml[1,0+9]..[1,0+21]) (opentyp.ml[1,0+9]..[1,0+21])
        ptype_params =
          []
        ptype_cstrs =
          []
        ptype_kind =
          Ptype_abstract
        ptype_private = Public
        ptype_manifest =
          Some
            core_type (opentyp.ml[1,0+9]..[1,0+21])
              Ptyp_object Closed
                method f
                  core_type (opentyp.ml[1,0+12]..[1,0+15])
                    Ptyp_constr "int" (opentyp.ml[1,0+12]..[1,0+15])
                    []
    ]
]