Dump parsetree without throughing away module type annotation.
In 4.01.0 all recursive modules require in explicit module type annotation
(https://github.com/ocaml/ocaml/commit/d32b1900). Camlp5 was throughing away
module type during dump of parsetree.

Demo:

$ ocamlfind ocamlc -dparsetree recmod.ml
[
  structure_item (recmod.ml[1,0+0]..[1,0+35])
    Pstr_recmodule
    [
      "A" (recmod.ml[1,0+11]..[1,0+12])
        module_expr (recmod.ml[1,0+13]..[1,0+35])
          Pmod_constraint
          module_expr (recmod.ml[1,0+25]..[1,0+35])
            Pmod_structure
            []
          module_type (recmod.ml[1,0+15]..[1,0+22])
            Pmty_signature
            []
    ]
]

$ ocamlfind ocamlc -dparsetree recmod.ml -pp etc/camlp5o
[
  structure_item (recmod.ml[1,0+0]..[1,0+35])
    Pstr_recmodule
    [
      "A" (_none_[1,0+-1]..[1,0+-1]) ghost
        module_expr (recmod.ml[1,0+25]..[1,0+35])
          Pmod_structure
          []
    ]
]

File "recmod.ml", line 1, characters 25-35:
Error: Recursive modules require an explicit module type.
$ cat recmod.ml
module rec A : sig end = struct end